spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: study
    password: 1111

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400