spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: study
    password: 1111

jwt:
  header: Authorization
  secret: Y2F0Y2hvby1wcm9qZWN0LXNlY3JldC1rZXkK
  token-validity-in-seconds: 86400