spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/catdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: study
    password: 1111
jwt:
  header: Authorization
  secret: 4oCYY2F0LXNlcnZlci1hcHAtY2F0Y2hvby1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWhheWVvbi1zcHJpbmctYm9vdC1qd3Qtc2VjcmV04oCZCg==
  token-validity-in-seconds: 86400